# Generated by Django 4.2.13 on 2024-07-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('created_for', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('optionA', models.CharField(max_length=255)),
                ('optionB', models.CharField(max_length=255)),
                ('optionC', models.CharField(max_length=255)),
                ('optionD', models.CharField(max_length=255)),
                ('correct_option', models.CharField(max_length=1)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university_id', models.BigIntegerField()),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('response_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('chosen_choice', models.CharField(max_length=1)),
                ('timestamp', models.DateTimeField()),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questions')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.user')),
            ],
        ),
    ]
