# Generated by Django 4.2.13 on 2024-07-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_no_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_username', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='cdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
