# Generated by Django 4.2.13 on 2024-07-06 12:17

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course_name',
            field=models.CharField(default='Engg.', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 12, 17, 50, 419915, tzinfo=datetime.timezone.utc)),
        ),
    ]
