# Generated by Django 4.2.13 on 2024-07-06 13:48

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_alter_exam_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 13, 48, 35, 358329, tzinfo=datetime.timezone.utc)),
        ),
    ]
