# Generated by Django 4.2.13 on 2024-07-10 11:40

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_user_auth_token_alter_exam_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 24, 11, 40, 50, 287934, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='university_id',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
