# Generated by Django 4.2.13 on 2024-07-17 15:13

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_user_marks_alter_exam_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 15, 13, 21, 582848, tzinfo=datetime.timezone.utc)),
        ),
    ]
