# Generated by Django 4.2.13 on 2024-07-21 03:31

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_remove_studentresponse_question_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='prefix',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 3, 31, 2, 578682, tzinfo=datetime.timezone.utc)),
        ),
    ]
