# Generated by Django 4.2.13 on 2024-07-21 04:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_exam_prefix_alter_exam_valid_till'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_for',
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 4, 25, 55, 551776, tzinfo=datetime.timezone.utc)),
        ),
    ]
