# Generated by Django 4.2.13 on 2024-07-21 04:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_alter_exam_valid_till_alter_user_university_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='student_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='university_email',
            field=models.EmailField(default='None', max_length=254),
        ),
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 4, 46, 4, 751477, tzinfo=datetime.timezone.utc)),
        ),
    ]
