# Generated by Django 4.2.13 on 2024-07-21 04:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_remove_user_username_user_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 4, 4, 58, 50, 798077, tzinfo=datetime.timezone.utc)),
        ),
    ]
