# Generated by Django 4.2.13 on 2024-07-22 11:49

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_exam_time_per_question_alter_exam_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 11, 49, 11, 965329, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='NA', max_length=10, unique=True),
        ),
    ]
