# Generated by Django 4.2.13 on 2024-07-22 12:03

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0027_alter_exam_valid_till_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 3, 51, 788901, tzinfo=datetime.timezone.utc)),
        ),
    ]
