# Generated by Django 4.2.13 on 2024-07-22 12:28

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_alter_exam_valid_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='valid_till',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 28, 29, 227407, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='exam_prefix',
            field=models.CharField(default='NA', max_length=3, unique=True),
        ),
    ]
