# Generated by Django 4.2.13 on 2024-08-05 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0031_alter_exam_valid_till_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="valid_till",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 19, 9, 38, 55, 890890, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
