# Generated by Django 4.2.13 on 2024-08-05 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0032_alter_exam_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="valid_till",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 19, 9, 39, 55, 977742, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
