# Generated by Django 4.2.13 on 2024-08-06 06:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0034_alter_exam_valid_till"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exam",
            name="valid_till",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 8, 20, 6, 3, 52, 149246, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
